package applicationImen;

import javafx.fxml.FXML;

import javafx.scene.text.Text;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.layout.AnchorPane;

import javafx.scene.image.ImageView;

import javafx.scene.input.MouseEvent;

public class ProfileuserController {
	@FXML
	private ImageView magic;
	@FXML
	private AnchorPane magicbar;
	@FXML
	private ImageView myimage;
	@FXML
	private ImageView magic2;
	@FXML
	private Text myname;
	@FXML
	private Text mylastname;
	@FXML
	private Button profil;
	@FXML
	private Button ownspace;
	@FXML
	private Button home;
	@FXML
	private Button message;
	@FXML
	private Button visuala;
	@FXML
	private Button musicb;
	@FXML
	private Button eventb;
	@FXML
	private Button tunisianc;

	// Event Listener on ImageView[#magic].onMouseMoved
	@FXML
	public void magic(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#magic2].onMouseMoved
	@FXML
	public void magic2(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#profil].onAction
	@FXML
	public void profil(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#ownspace].onAction
	@FXML
	public void Myownspace(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#home].onAction
	@FXML
	public void home(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#message].onAction
	@FXML
	public void message(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#visuala].onAction
	@FXML
	public void visualart(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#musicb].onAction
	@FXML
	public void music(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#eventb].onAction
	@FXML
	public void Event(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#tunisianc].onAction
	@FXML
	public void Tunisiancraft(ActionEvent event) {
		// TODO Autogenerated
	}
}
