package application;

import java.net.URL;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.Date;
import java.util.List;
import java.util.ResourceBundle;

import javax.naming.InitialContext;
import javax.naming.NamingException;

import com.jfoenix.controls.JFXButton;

import entities.Admin;
import entities.Category;
import entities.User;
import javafx.event.ActionEvent;
import javafx.event.Event;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Alert;
import javafx.scene.control.ListView;
import javafx.scene.control.TabPane;
import javafx.scene.control.TableColumn;
import javafx.scene.control.TableView;
import javafx.scene.control.TextField;
import javafx.scene.control.Alert.AlertType;
import javafx.util.Duration;
import services.ForumManagementRemote;
import services.UserManagmentRemote;
import javafx.animation.TranslateTransition;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;;
/**
*
* @author InesWanen
*/
public class MenuAdminController  implements Initializable {
	@FXML
	private JFXButton ManageForum;
	@FXML
	private TabPane tabpane;
	@FXML
	private TextField addCategoryTF;
	@FXML
	private JFXButton addCategoryButton;
	@FXML
	private TableView table;
	@FXML
	private TableColumn name;
    ObservableList <Category> data = FXCollections.observableArrayList();

	
	InitialContext ctx;
	public static ForumManagementRemote proxy ;
	public static UserManagmentRemote userManagement;
	

	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub
		tabpane.setVisible(false);
		 try {
				ctx = new InitialContext();
				 proxy = (ForumManagementRemote)ctx.lookup("/Fanny-ear/Fanny-ejb/ForumManagement!services.ForumManagementRemote");
				 userManagement =(UserManagmentRemote) ctx.lookup("/Fanny-ear/Fanny-ejb/UserManagment!services.UserManagmentRemote");
					Category p = new Category();
									
			} catch (NamingException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		 
		

		
	}
	

	// Event Listener on JFXButton[#ManageForum].onAction
	@FXML
	public void ManageForum(ActionEvent event) {
		// TODO Autogenerated
		TranslateTransition transition = new TranslateTransition();
		transition.setDuration(Duration.seconds(2));
		transition.setNode(ManageForum);
		transition.setToY(-150);
		transition.setToX(-200);
		/*to come back for initial position */
		//transition.setAutoReverse(true);
		//transition.setCycleCount(2);
		/*end*/
		transition.play();
		
		//event handler in input //lambda expression
		transition.setOnFinished((e)->{
			tabpane.setVisible(true);
			
			 List<Category> listCategories =proxy.findAllCategories();
				for ( Category c :listCategories)
				{
				System.out.println(c.getName());
				data.add(c);
				}
				table.setItems(data);
				
			
			
			
		});
		
	}
	@FXML
	public void addCategory(ActionEvent event) {
		// TODO Autogenerated
		Category c = new Category();
		User u = new User ();
		String name =addCategoryTF.getText();	
		if(name.length()==0)
		{
			Alert a = new Alert(AlertType.ERROR);
			a.setContentText("!!!");
			a.show();
		}
		else		
		{

		DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        Instant instant = now.atZone(ZoneId.systemDefault()).toInstant();     
		Date date = Date.from(instant);
		c.setAddedAt(date);
		c.setName(name);
	    c.setAddedBy((Admin)LoginController.userLogedIn);	
		proxy.addCategory(c);}

	}
	//@FXML
	//public void displayCategories(Event event) {
		//System.out.println(proxy.findAllCategories());
//	
//	//	List<Category> listCategories =proxy.findAllCategories();
//		for ( Category c :listCategories)
//		{
//		System.out.println(c);
//		}
//		//table.setItems(data);
//	}
	

}
