package applicationOussema;

import javafx.fxml.FXML;

import javafx.scene.input.MouseEvent;

public class DetailArtworkController2 {

	// Event Listener on Rating[#ratingg].onMouseClicked
	@FXML
	public void Rate(MouseEvent event) {
		// TODO Autogenerated
	}
}
